import "./globals.css";

// Note: This file should ideally be DELETED because app/[lang]/layout.tsx is your actual Root Layout.
// Having two files defining <html> and <body> causes hydration mismatches.
// I have removed the tags below to prevent the crash, but please delete this file.

export const metadata = {
  title: 'Website AEE',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
