import "./globals.css";

// Note: Ensure app/[lang]/layout.tsx serves as the root layout for your localized pages.
// If you see errors about multiple root layouts, you can safely delete this file 
// after verifying app/[lang]/layout.tsx defines <html> and <body>.

export const metadata = {
  title: 'Website AEE',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
